# Generated by Django 2.2.3 on 2023-03-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230302_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enlace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
    ]
