# Generated by Django 2.2.3 on 2023-03-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230302_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='enlace',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
